# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ee/pages/
image: ruby:latest

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install bundler
  - bundle install

stages:
  - test
  - build
  - deploy

qa_test:
  tags:
  - docker
  stage: test
  enviornment:
    name: qa
  script:
    - bundle exec jekyll doctor
  except:
    - release

qa_build:
  tags:
  - docker
  stage: build
  enviornment:
    name: qa
  script:
    - bundle exec jekyll build -d qa --strict_front_matter
  artifacts:
    paths:
      - qa
  except:
    - release

qa_deploy:
  image: python:latest
  tags:
  - docker
  stage: deploy
  enviornment:
    name: qa
  before_script:
    - pip install awscli
  script:
    - aws s3 cp ./qa arn:aws:s3:::ll-gitlab-jekyll-qa --recursive
  artifacts:
    paths:
      - qa
  except:
    - release
